version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biocad
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/biocad
      JWT_SECRET: your_jwt_secret
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  frontend:
    build: ./mobile
    container_name: frontend
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - backend

volumes:
  postgres_data:
